# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='TwitterProfile',
        ),
    ]
